### PR TITLE
Update the fortune of ngx_php7

### PR DESCRIPTION
**Pull request by rryqszq4**

### CODE REVIEW

**Comment by joanhey** [comment]
~Please could you create the PR in this branch: https://github.com/joanhey/FrameworkBenchmarks/tree/ngx_php~
I have already sent the PR of the new version. Also the travis test will be faster.

Will be better if we create the template in a different file and include it.

**Comment by joanhey** [comment]
From where load this file 
"/ngx_php7/t/lib/mysql.php" ??

From the same ngx_php ??

**Comment by joanhey** [comment]
Problem in the travis test:
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/576790214#L1775

Lua is using an ENV
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Lua/openresty/openresty.dockerfile#L57

The database is only in localhost when using vagrant. The rest are using an external db server.
Remember to use persistent connections.

**Comment by rryqszq4** [comment]
https://github.com/rryqszq4/ngx_php7/blob/master/t/lib/mysql.php , it is mysql driver file.
hope to test performance.

**Comment by joanhey** [comment]
Swoole is using an own method `gethostbyname()`
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/swoole/swoole-server.php#L228

**Comment by rryqszq4** [comment]
> Problem in the travis test:
> https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/576790214#L1775
> 
> Lua is using an ENV
> https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Lua/openresty/openresty.dockerfile#L57
> 
> The database is only in localhost when using vagrant. The rest are using an external db server.
> Remember to use persistent connections.

I probably understand this gap, and it may take some time to fix it.

**Comment by joanhey** [comment]
I will try to use an ENV for now.

**Pull request merged**
