### PR TITLE
Update the fortune again with gethostbyname.

### PR DESCRIPTION
**Pull request by rryqszq4**
Try ENV and getenv in php, but not success so use gethostbyname. And research env later.
Test and review, i think is pass.

### CODE REVIEW

**Comment by rryqszq4** [comment]
@joanhey 
Why my travis-ci(https://travis-ci.org/rryqszq4/FrameworkBenchmarks) not work, is it missing setting ?!~

**Comment by joanhey** [comment]
It's a complicated test, that try to only test the changes, and sometimes fail.
Also in a local PR will be very slow.
I try to test locally with the vagrant.

**Comment by joanhey** [comment]
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/577260668#L1809

**Comment by joanhey** [comment]
Perhaps use an Nginx var instead.

**Comment by rryqszq4** [comment]
> https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/577260668#L1809

Spelling mistake, should be DB_HOST.

**Comment by rryqszq4** [comment]
> Perhaps use an Nginx var instead.

http://nginx.org/en/docs/ngx_core_module.html#env
"By default, nginx removes all environment variables inherited from its parent process..."
I will research it later.

**Pull request merged**
